In [1]:
import tensorflow as tf

## tf.constant -->> immutable 

In [3]:
t=tf.constant([[1,2,3],
               [4,5,6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [4]:
t.shape


TensorShape([2, 3])

In [6]:
t.dtype

tf.int32

In [15]:
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [42]:
t+10 # this is not directly applied to t because its constnant

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [17]:
t*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)>

In [20]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [28]:
t @ tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [32]:
t_float=tf.cast(t, tf.float32)

In [34]:
tf.exp(t_float) # exp take float

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[  2.7182817,   7.389056 ,  20.085537 ],
       [ 54.59815  , 148.41316  , 403.4288   ]], dtype=float32)>

In [36]:
tf.sqrt(t_float)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1.       , 1.4142135, 1.7320508],
       [2.       , 2.236068 , 2.4494898]], dtype=float32)>

## t.variable -->> mutable

In [39]:
v=tf.Variable([[1,2,3],[4,5,6]])
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [43]:
v.assign(v*2) ## this assigns the changes directly for the v because its a variable 


<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

In [44]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 4,  8, 12],
       [16, 20, 24]], dtype=int32)>

## other structures 

### sparse

In [53]:
import tensorflow as tf

sparse = tf.SparseTensor(indices=[[0, 2], [1, 1], [2, 0]],
                         values=[1, 2, 3],
                         dense_shape=[3, 3])

print("Sparse tensor:", sparse)
print("Convert back to dense:\n", tf.sparse.to_dense(sparse))


Sparse tensor: SparseTensor(indices=tf.Tensor(
[[0 2]
 [1 1]
 [2 0]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))
Convert back to dense:
 tf.Tensor(
[[0 0 1]
 [0 2 0]
 [3 0 0]], shape=(3, 3), dtype=int32)


### stack

In [47]:
ta = tf.TensorArray(dtype=tf.float32, size=3)

# Write values
ta = ta.write(0, [1.0, 2.0])
ta = ta.write(1, [3.0, 4.0])
ta = ta.write(2, [5.0, 6.0])

# Stack back into a single tensor
stacked = ta.stack()
print(stacked)
# Output: [[1, 2], [3, 4], [5, 6]]


tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


### ragged (different lenghts)

In [48]:
rt = tf.ragged.constant([[1, 2, 3],
                         [4, 5],
                         [6]])
print(rt)
# Output: <tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

print(rt[1])  # Row 1 = [4, 5]


<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>
tf.Tensor([4 5], shape=(2,), dtype=int32)


### strings

In [49]:
st = tf.constant(["hello", "café"])  
print(st)  # UTF-8 encoded internally

# String ops
upper = tf.strings.upper(st)
print(upper.numpy())  # [b'HELLO' b'CAF\xc3\x89']


tf.Tensor([b'hello' b'caf\xc3\xa9'], shape=(2,), dtype=string)
[b'HELLO' b'CAF\xc3\xa9']


### join


In [50]:
s1 = tf.constant([[1, 2], [3, 4]])
s2 = tf.constant([[2, 3], [4, 5]])

union = tf.sets.union(s1, s2)
print("Union:", tf.sparse.to_dense(union))
# Output: [[1 2 3], [3 4 5]]


Union: tf.Tensor(
[[1 2 3]
 [3 4 5]], shape=(2, 3), dtype=int32)


## custom loss

In [56]:
def huber_fn(y_true, y_pred):
 error = y_true - y_pred
 is_small_error = tf.abs(error) < 1
 squared_loss = tf.square(error) / 2
 linear_loss  = tf.abs(error) - 0.5
 return tf.where(is_small_error, squared_loss, linear_loss)

In [62]:
import tensorflow as tf

y_true = tf.constant([1.0, 2.0, 3.0])   # ground truth
y_pred = tf.constant([1.5, 2.5, 2.0])   # predictions

loss = huber_fn(y_true, y_pred)
print(loss)


tf.Tensor([0.125 0.125 0.5  ], shape=(3,), dtype=float32)


In [ ]:
## using the custom function with model traning
model.compile(loss=huber_fn, optimizer="nadam")
model.fit(X_train, y_train, [...])

In [ ]:
## save the model with custom loss function
model = tf.keras.models.load_model("my_model_with_a_custom_loss",
custom_objects={"huber_fn": huber_fn})

## Custom Activation Functions, Regularizers,and Constraints

In [63]:
 def my_softplus(z):
     return tf.math.log(1.0 + tf.exp(z))
     
 def my_l1_regularizer(weights):
     return tf.reduce_sum(tf.abs(0.01 * weights))
     
 def my_positive_weights(weights):  # return value is just tf.nn.relu(weights)
     return tf.where(weights < 0., tf.zeros_like(weights), weights)

In [64]:
layer = tf.keras.layers.Dense(1, activation=my_softplus,kernel_regularizer=my_l1_regularizer,kernel_constraint=my_positive_weights)